# Generated by Django 5.2.1 on 2025-05-29 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Grupo')),
                ('type', models.CharField(choices=[('r', 'Receita'), ('e', 'Despesa')], max_length=1, verbose_name='Tipo da Transação')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.TimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Grupo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Descrição')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.TimeField(auto_now=True, verbose_name='Atualizado em')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Descrição',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('begin', models.TimeField(verbose_name='Início')),
                ('end', models.TimeField(verbose_name='Final')),
                ('obs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.TimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.description', verbose_name='Descrição')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.group', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lançamento recorrente',
                'ordering': ['begin'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('created_at', models.TimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.TimeField(auto_now=True, verbose_name='Atualizado em')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.description', verbose_name='Descrição')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.group', verbose_name='Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'ordering': ['created_at'],
            },
        ),
    ]
