# Generated by Django 5.2.1 on 2025-06-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_description_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Category',
        ),
    ]
