# Generated by Django 5.2.1 on 2025-06-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_group_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Descrição'},
        ),
        migrations.RenameField(
            model_name='description',
            old_name='group',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recurring',
            old_name='group',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='group',
            new_name='category',
        ),
    ]
