# Generated by Django 5.2.1 on 2025-06-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_category_options_alter_description_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recurring',
        ),
    ]
